version: '3.1'
services:
  stats-server:
    build: stat-service
    image: stat_service_image
    container_name:  stat_service_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ExploreWithMeStat
      - SPRING_DATASOURCE_USERNAME=Alexey
      - SPRING_DATASOURCE_PASSWORD=AlexeyVLZ

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=Alexey
      - POSTGRES_PASSWORD=AlexeyVLZ
      - POSTGRES_DB=ExploreWithMeStat

  ewm-service:
    build: main-service
    image: main_service_image
    container_name: main_service_container
    ports:
      - "8080:8080"
    depends_on:
          - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/exploreWithMeMain
      - SPRING_DATASOURCE_USERNAME=Alexey
      - SPRING_DATASOURCE_PASSWORD=AlexeyVLZ

  ewm-db:
    image: postgres:14-alpine
    container_name: main_db_container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_USER=Alexey
      - POSTGRES_PASSWORD=AlexeyVLZ
      - POSTGRES_DB=exploreWithMeMain
