CREATE TABLE IF NOT EXISTS statistics (
    statistic_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app                 VARCHAR NOT NULL,
    uri                 VARCHAR NOT NULL,
    ip                  VARCHAR NOT NULL,
    timestamp_statistic TIMESTAMP NOT NULL,
    CONSTRAINT          pk_statistic PRIMARY KEY (statistic_id)
);

